
    create table custom_exercises (
        equipment varchar(255),
        id varchar(255) not null,
        muscle varchar(255),
        name varchar(255),
        user_email varchar(255),
        primary key (id)
    );

    create table food_logs (
        carbs float(53) not null,
        fat float(53) not null,
        kcal float(53) not null,
        log_date date not null,
        meal_index integer not null,
        protein float(53) not null,
        quantity float(53) not null,
        id bigint generated by default as identity,
        product varchar(255) not null,
        user_email varchar(255) default 'raclosdev@gmail.com' not null,
        primary key (id)
    );

    create table meals (
        carbs_pct float(53),
        fat_pct float(53),
        fixed_carbs float(53),
        fixed_fat float(53),
        fixed_protein float(53),
        is_default boolean,
        protein_pct float(53),
        sort_order integer not null,
        end_time varchar(5),
        start_time varchar(5),
        id bigint generated by default as identity,
        icon varchar(255) not null,
        name varchar(255) not null,
        user_email varchar(255),
        primary key (id)
    );

    create table recipes (
        total_carbs float(53) not null,
        total_fat float(53) not null,
        total_kcal float(53) not null,
        total_protein float(53) not null,
        id bigint generated by default as identity,
        description TEXT,
        name varchar(255) not null,
        user_email varchar(255) not null,
        primary key (id)
    );

    create table refresh_tokens (
        expiry_date timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        email varchar(255) not null,
        name varchar(255),
        picture varchar(255),
        token varchar(255) not null unique,
        primary key (id)
    );

    create table saved_foods (
        carbs_per100g float(53) not null,
        fat_per100g float(53) not null,
        kcal_per100g float(53) not null,
        protein_per100g float(53) not null,
        serving_size float(53),
        id bigint generated by default as identity,
        last_used_at timestamp(6),
        brand varchar(255),
        name varchar(255) not null,
        serving_label varchar(255),
        user_email varchar(255) not null,
        primary key (id)
    );

    create table steps_entries (
        date date not null,
        steps integer not null,
        id bigint generated by default as identity,
        user_email varchar(255) not null,
        primary key (id),
        unique (user_email, date)
    );

    create table user_settings (
        custom_carbs_grams float(53),
        custom_carbs_pct float(53),
        custom_fat_grams float(53),
        custom_fat_pct float(53),
        custom_protein_grams float(53),
        custom_protein_pct float(53),
        goal_weight float(53) not null,
        kcal integer not null,
        start_date date not null,
        start_weight float(53) not null,
        weekly_goal float(53) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        macro_strategy varchar(20),
        user_email varchar(255) default 'raclosdev@gmail.com' not null unique,
        workout_data TEXT,
        primary key (id)
    );

    create table weight_entries (
        date date not null,
        weight float(53) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        user_email varchar(255) not null,
        primary key (id),
        unique (user_email, date)
    );

    create table workout_exercises (
        order_index integer,
        exercise_id varchar(255),
        id varchar(255) not null,
        notes TEXT,
        superset_id varchar(255),
        workout_id varchar(255) not null,
        primary key (id)
    );

    create table workout_sets (
        completed boolean,
        order_index integer,
        distance varchar(255),
        duration varchar(255),
        id varchar(255) not null,
        reps varchar(255),
        rpe varchar(255),
        type varchar(255),
        weight varchar(255),
        workout_exercise_id varchar(255) not null,
        primary key (id)
    );

    create table workout_template_exercises (
        exercise_id varchar(255),
        template_id varchar(255) not null
    );

    create table workout_templates (
        id varchar(255) not null,
        name varchar(255) not null,
        user_email varchar(255) not null,
        primary key (id)
    );

    create table workouts (
        finished_at bigint,
        started_at bigint,
        id varchar(255) not null,
        name varchar(255) not null,
        notes TEXT,
        user_email varchar(255) not null,
        primary key (id)
    );

    alter table if exists workout_exercises 
       add constraint FKd2ychryarm8gp13672lojwr78 
       foreign key (workout_id) 
       references workouts;

    alter table if exists workout_sets 
       add constraint FK344fsmivnj500l86uf14e2yrm 
       foreign key (workout_exercise_id) 
       references workout_exercises;

    alter table if exists workout_template_exercises 
       add constraint FKmshwl2pqww78k84yxa1ok29xd 
       foreign key (template_id) 
       references workout_templates;
