export const GENERIC_FOODS = [
  {
    id: 'gen-platano',
    name: 'Plátano',
    brand: 'Genérico',
    kcal: 89,
    protein: 1.1,
    carbs: 22.8,
    fat: 0.3,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸŒ',
  },
  {
    id: 'gen-manzana',
    name: 'Manzana',
    brand: 'Genérico',
    kcal: 52,
    protein: 0.3,
    carbs: 13.8,
    fat: 0.2,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸŽ',
  },
  {
    id: 'gen-pollo',
    name: 'Pechuga de Pollo (Cruda)',
    brand: 'Genérico',
    kcal: 110,
    protein: 23.1,
    carbs: 0,
    fat: 1.2,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ—',
  },
  {
    id: 'gen-pavo',
    name: 'Pechuga de Pavo (Cruda)',
    brand: 'Genérico',
    kcal: 104,
    protein: 24,
    carbs: 0,
    fat: 1,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¦ƒ',
  },
  {
    id: 'gen-ternera',
    name: 'Carne de Ternera (Magra)',
    brand: 'Genérico',
    kcal: 143,
    protein: 26,
    carbs: 0,
    fat: 3.5,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¥©',
  },
  {
    id: 'gen-cerdo',
    name: 'Lomo de Cerdo',
    brand: 'Genérico',
    kcal: 143,
    protein: 21,
    carbs: 0,
    fat: 6,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¥“',
  },
  {
    id: 'gen-huevo',
    name: 'Huevo entero',
    brand: 'Genérico',
    kcal: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    servingSize: 55,
    servingLabel: 'ud',
    image: 'ðŸ¥š',
  },
  {
    id: 'gen-claras',
    name: 'Claras de Huevo',
    brand: 'Genérico',
    kcal: 52,
    protein: 11,
    carbs: 0.7,
    fat: 0.2,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ³',
  },
  {
    id: 'gen-arroz-blanco',
    name: 'Arroz Blanco (Crudo)',
    brand: 'Genérico',
    kcal: 360,
    protein: 7,
    carbs: 79,
    fat: 0.6,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸš',
  },
  {
    id: 'gen-pasta',
    name: 'Pasta / Macarrones (Crudo)',
    brand: 'Genérico',
    kcal: 350,
    protein: 12,
    carbs: 71,
    fat: 1.5,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ',
  },
  {
    id: 'gen-patata',
    name: 'Patata (Cruda)',
    brand: 'Genérico',
    kcal: 77,
    protein: 2,
    carbs: 17,
    fat: 0.1,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¥”',
  },
  {
    id: 'gen-boniato',
    name: 'Boniato / Batata (Cruda)',
    brand: 'Genérico',
    kcal: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ ',
  },
  {
    id: 'gen-avena',
    name: 'Copos de Avena',
    brand: 'Genérico',
    kcal: 389,
    protein: 16.9,
    carbs: 66.3,
    fat: 6.9,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¥£',
  },
  {
    id: 'gen-pan',
    name: 'Pan Blanco',
    brand: 'Genérico',
    kcal: 265,
    protein: 9,
    carbs: 49,
    fat: 3.2,
    servingSize: 100,
    servingLabel: 'g',
    image: 'ðŸ¥–',
  },
  {
    id: 'gen-leche-entera',
    name: 'Leche Entera',
    brand: 'Genérico',
    kcal: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.6,
    servingSize: 100,
    servingLabel: 'ml',
    image: 'ðŸ¥›',
  },
  {
    id: 'gen-leche-semi',
    name: 'Leche Semidesnatada',
    brand: 'Genérico',
    kcal: 47,
    protein: 3.4,
    carbs: 4.8,
    fat: 1.6,
    servingSize: 100,
    servingLabel: 'ml',
    image: 'ðŸ¥›',
  },
  {
    id: 'gen-yogur',
    name: 'Yogur Natural',
    brand: 'Genérico',
    kcal: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    servingSize: 125,
    servingLabel: 'g',
    image: 'ðŸ¶',
  },
  {
    id: 'gen-atun-lata',
    name: 'Atún al Natural (Escurrido)',
    brand: 'Genérico',
    kcal: 99,
    protein: 23,
    carbs: 0,
    fat: 0.8,
    servingSize: 56,
    servingLabel: 'g',
    image: 'ðŸŸ',
  },
  {
    id: 'gen-aceite-oliva',
    name: 'Aceite de Oliva Virgen Extra',
    brand: 'Genérico',
    kcal: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    servingSize: 10,
    servingLabel: 'cdta',
    image: 'ðŸ«’',
  },
  {
    id: 'gen-almendras',
    name: 'Almendras',
    brand: 'Genérico',
    kcal: 579,
    protein: 21,
    carbs: 21,
    fat: 49,
    servingSize: 30,
    servingLabel: 'g',
    image: 'ðŸŒ°',
  },
  {
    id: 'gen-nueces',
    name: 'Nueces',
    brand: 'Genérico',
    kcal: 654,
    protein: 15,
    carbs: 13,
    fat: 65,
    servingSize: 30,
    servingLabel: 'g',
    image: 'ðŸ¥œ',
  },
];




